import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Inserindo dados na tabela tipoConserto
  await prisma.mecanico.createMany({
    data: [
      { nome: 'Carlos', idade: 25, tempoPorDia: 8, nivelComplexidade: 2 },
      { nome: 'Ana', idade: 30, tempoPorDia: 8, nivelComplexidade: 1 },
      { nome: 'João', idade: 22, tempoPorDia: 8, nivelComplexidade: 3 },
      { nome: 'Mariana', idade: 28, tempoPorDia: 8, nivelComplexidade: 2 },
      { nome: 'Pedro', idade: 35, tempoPorDia: 8, nivelComplexidade: 1 },
      { nome: 'Julia', idade: 19, tempoPorDia: 8, nivelComplexidade: 3 },
      { nome: 'Ricardo', idade: 45, tempoPorDia: 8, nivelComplexidade: 1 },
      { nome: 'Fernanda', idade: 27, tempoPorDia: 8, nivelComplexidade: 2 },
      { nome: 'Thiago', idade: 32, tempoPorDia: 8, nivelComplexidade: 3 },
      { nome: 'Laura', idade: 24, tempoPorDia: 8, nivelComplexidade: 1 },
    ],
  });
  await prisma.tipoConserto.createMany({
    data: [
      { id: 1, tempoEstimado: 2 },
      { id: 2, tempoEstimado: 4 },
      { id: 3, tempoEstimado: 3 },
      { id: 4, tempoEstimado: 5 },
      { id: 5, tempoEstimado: 1 },
    ],
  });
  // Inserindo dados na tabela consertoDeMotos
  await prisma.consertoDeMotos.createMany({
    data: [
      {
        motoId: 34,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(7 / 10 / 2024),
        mecanicoId: 2,
      },
      {
        motoId: 294,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: 3,
        dataEntrada: new Date(7 / 10 / 2024),
        mecanicoId: 1,
      },
      {
        motoId: 314,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 2,
        dataEntrada: new Date(7 / 10 / 2024),
        mecanicoId: 7,
      },
      {
        motoId: 488,
        complexidadeDoConserto: 3,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(7 / 10 / 2024),
        mecanicoId: 6,
      },
      {
        motoId: 123,
        complexidadeDoConserto: 2,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(7 / 10 / 2024),
        mecanicoId: 4,
      },
      {
        motoId: 221,
        complexidadeDoConserto: 1,
        tipoConsertoId: 1,
        tempoReal: 2,
        dataEntrada: new Date(7 / 10 / 2024),
        mecanicoId: 10,
      },
      {
        motoId: 456,
        complexidadeDoConserto: 3,
        tipoConsertoId: 5,
        tempoReal: 5,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 9,
      },
      {
        motoId: 89,
        complexidadeDoConserto: 2,
        tipoConsertoId: 2,
        tempoReal: 6,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 8,
      },
      {
        motoId: 190,
        complexidadeDoConserto: 1,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 7,
      },
      {
        motoId: 402,
        complexidadeDoConserto: 2,
        tipoConsertoId: 3,
        tempoReal: 3,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 1,
      },
      {
        motoId: 76,
        complexidadeDoConserto: 1,
        tipoConsertoId: 1,
        tempoReal: 4,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 10,
      },
      {
        motoId: 320,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 5,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 8,
      },
      {
        motoId: 145,
        complexidadeDoConserto: 3,
        tipoConsertoId: 2,
        tempoReal: 6,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 6,
      },
      {
        motoId: 67,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 1,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 2,
      },
      {
        motoId: 290,
        complexidadeDoConserto: 2,
        tipoConsertoId: 4,
        tempoReal: 2,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 4,
      },
      {
        motoId: 112,
        complexidadeDoConserto: 1,
        tipoConsertoId: 5,
        tempoReal: 4,
        dataEntrada: new Date(7 / 11 / 2024),
        mecanicoId: 7,
      },
      {
        motoId: 404,
        complexidadeDoConserto: 3,
        tipoConsertoId: 2,
        tempoReal: 1,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 9,
      },
      {
        motoId: 310,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 2,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 3,
      },
      {
        motoId: 22,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: 4,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 8,
      },
      {
        motoId: 459,
        complexidadeDoConserto: 3,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 6,
      },
      {
        motoId: 134,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 3,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 4,
      },
      {
        motoId: 293,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 2,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 10,
      },
      {
        motoId: 378,
        complexidadeDoConserto: 3,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 6,
      },
      {
        motoId: 101,
        complexidadeDoConserto: 1,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 7,
      },
      {
        motoId: 488,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: 3,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 8,
      },
      {
        motoId: 376,
        complexidadeDoConserto: 3,
        tipoConsertoId: 5,
        tempoReal: 5,
        dataEntrada: new Date(7 / 12 / 2024),
        mecanicoId: 9,
      },
      {
        motoId: 184,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 6,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 2,
      },
      {
        motoId: 231,
        complexidadeDoConserto: 2,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 1,
      },
      {
        motoId: 498,
        complexidadeDoConserto: 1,
        tipoConsertoId: 4,
        tempoReal: 2,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 10,
      },
      {
        motoId: 345,
        complexidadeDoConserto: 3,
        tipoConsertoId: 1,
        tempoReal: 1,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 9,
      },
      {
        motoId: 109,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 3,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 4,
      },
      {
        motoId: 203,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 2,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 7,
      },
      {
        motoId: 402,
        complexidadeDoConserto: 3,
        tipoConsertoId: 2,
        tempoReal: 4,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 3,
      },
      {
        motoId: 187,
        complexidadeDoConserto: 1,
        tipoConsertoId: 5,
        tempoReal: 1,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 2,
      },
      {
        motoId: 291,
        complexidadeDoConserto: 2,
        tipoConsertoId: 4,
        tempoReal: 3,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 8,
      },
      {
        motoId: 412,
        complexidadeDoConserto: 3,
        tipoConsertoId: 1,
        tempoReal: 5,
        dataEntrada: new Date(7 / 13 / 2024),
        mecanicoId: 6,
      },
      {
        motoId: 175,
        complexidadeDoConserto: 2,
        tipoConsertoId: 3,
        tempoReal: 6,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 4,
      },
      {
        motoId: 64,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 4,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 7,
      },
      {
        motoId: 344,
        complexidadeDoConserto: 3,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 3,
      },
      {
        motoId: 220,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 3,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 1,
      },
      {
        motoId: 128,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 2,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 10,
      },
      {
        motoId: 376,
        complexidadeDoConserto: 3,
        tipoConsertoId: 2,
        tempoReal: 1,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 9,
      },
      {
        motoId: 401,
        complexidadeDoConserto: 1,
        tipoConsertoId: 4,
        tempoReal: 4,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 2,
      },
      {
        motoId: 147,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: 5,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 8,
      },
      {
        motoId: 338,
        complexidadeDoConserto: 3,
        tipoConsertoId: 3,
        tempoReal: 6,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 6,
      },
      {
        motoId: 178,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 1,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 7,
      },
      {
        motoId: 234,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 3,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 4,
      },
      {
        motoId: 97,
        complexidadeDoConserto: 3,
        tipoConsertoId: 4,
        tempoReal: 2,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 9,
      },
      {
        motoId: 120,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(7 / 14 / 2024),
        mecanicoId: 3,
      },
      {
        motoId: 221,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: null,
        dataEntrada: new Date(7 / 15 / 2024),
        mecanicoId: null,
      },
      {
        motoId: 154,
        complexidadeDoConserto: 3,
        tipoConsertoId: 5,
        tempoReal: null,
        dataEntrada: new Date(7 / 15 / 2024),
        mecanicoId: null,
      },
      {
        motoId: 299,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: null,
        dataEntrada: new Date(7 / 15 / 2024),
        mecanicoId: null,
      },
      {
        motoId: 432,
        complexidadeDoConserto: 2,
        tipoConsertoId: 4,
        tempoReal: null,
        dataEntrada: new Date(7 / 15 / 2024),
        mecanicoId: null,
      },
      {
        motoId: 75,
        complexidadeDoConserto: 3,
        tipoConsertoId: 3,
        tempoReal: null,
        dataEntrada: new Date(7 / 15 / 2024),
        mecanicoId: null,
      },
    ],
  });
}

main()
  .then(() => {
    console.log('Seed data created');
  })
  .catch((error) => {
    console.error(error);
  })
  .finally(() => {
    prisma.$disconnect();
  });
