import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.mecanico.deleteMany({});
  await prisma.mecanico.createMany({
    data: [
      { nome: 'Carlos', idade: 25, tempoPorDia: 8, nivelComplexidade: 2 },
      { nome: 'Ana', idade: 30, tempoPorDia: 8, nivelComplexidade: 1 },
      { nome: 'João', idade: 22, tempoPorDia: 8, nivelComplexidade: 3 },
      { nome: 'Mariana', idade: 28, tempoPorDia: 8, nivelComplexidade: 2 },
      { nome: 'Pedro', idade: 35, tempoPorDia: 8, nivelComplexidade: 1 },
      { nome: 'Julia', idade: 19, tempoPorDia: 8, nivelComplexidade: 3 },
      { nome: 'Ricardo', idade: 45, tempoPorDia: 8, nivelComplexidade: 1 },
      { nome: 'Fernanda', idade: 27, tempoPorDia: 8, nivelComplexidade: 2 },
      { nome: 'Thiago', idade: 32, tempoPorDia: 8, nivelComplexidade: 3 },
      { nome: 'Laura', idade: 24, tempoPorDia: 8, nivelComplexidade: 1 },
    ],
  });

  await prisma.tipoConserto.deleteMany({});
  await prisma.tipoConserto.createMany({
    data: [
      { id: 1, tempoEstimado: 2 },
      { id: 2, tempoEstimado: 4 },
      { id: 3, tempoEstimado: 3 },
      { id: 4, tempoEstimado: 5 },
      { id: 5, tempoEstimado: 1 },
    ],
  });

  await prisma.moto.deleteMany({});
  const motos = [
    {
      id: 34,
      marca: 'Honda',
      modelo: 'CB 500',
      ano: 2019,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 294,
      marca: 'Yamaha',
      modelo: 'Fazer 250',
      ano: 2020,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 314,
      marca: 'Suzuki',
      modelo: 'GSX-R750',
      ano: 2018,
      cor: 'Azul',
      cpf: null,
    },
    {
      id: 488,
      marca: 'Kawasaki',
      modelo: 'Ninja 400',
      ano: 2021,
      cor: 'Verde',
      cpf: null,
    },
    {
      id: 123,
      marca: 'Ducati',
      modelo: 'Monster 821',
      ano: 2020,
      cor: 'Amarela',
      cpf: null,
    },
    {
      id: 221,
      marca: 'BMW',
      modelo: 'S 1000 RR',
      ano: 2019,
      cor: 'Branca',
      cpf: null,
    },
    {
      id: 456,
      marca: 'Triumph',
      modelo: 'Street Triple',
      ano: 2021,
      cor: 'Cinza',
      cpf: null,
    },
    {
      id: 89,
      marca: 'Harley-Davidson',
      modelo: 'Iron 883',
      ano: 2017,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 190,
      marca: 'KTM',
      modelo: 'Duke 390',
      ano: 2019,
      cor: 'Laranja',
      cpf: null,
    },
    {
      id: 402,
      marca: 'Yamaha',
      modelo: 'MT-07',
      ano: 2020,
      cor: 'Azul',
      cpf: null,
    },
    {
      id: 76,
      marca: 'Honda',
      modelo: 'CBR 1000RR',
      ano: 2021,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 320,
      marca: 'Suzuki',
      modelo: 'Hayabusa',
      ano: 2018,
      cor: 'Prata',
      cpf: null,
    },
    {
      id: 145,
      marca: 'Ducati',
      modelo: 'Panigale V4',
      ano: 2020,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 67,
      marca: 'BMW',
      modelo: 'R 1250 GS',
      ano: 2021,
      cor: 'Azul',
      cpf: null,
    },
    {
      id: 290,
      marca: 'Kawasaki',
      modelo: 'Z900',
      ano: 2019,
      cor: 'Verde',
      cpf: null,
    },
    {
      id: 112,
      marca: 'Triumph',
      modelo: 'Tiger 900',
      ano: 2020,
      cor: 'Cinza',
      cpf: null,
    },
    {
      id: 404,
      marca: 'Harley-Davidson',
      modelo: 'Fat Bob',
      ano: 2021,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 310,
      marca: 'KTM',
      modelo: 'Adventure 390',
      ano: 2020,
      cor: 'Laranja',
      cpf: null,
    },
    {
      id: 22,
      marca: 'Yamaha',
      modelo: 'R3',
      ano: 2018,
      cor: 'Azul',
      cpf: null,
    },
    {
      id: 459,
      marca: 'Suzuki',
      modelo: 'GSX-S750',
      ano: 2020,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 134,
      marca: 'Ducati',
      modelo: 'Scrambler',
      ano: 2019,
      cor: 'Amarela',
      cpf: null,
    },
    {
      id: 293,
      marca: 'Honda',
      modelo: 'Africa Twin',
      ano: 2021,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 378,
      marca: 'BMW',
      modelo: 'S 1000 XR',
      ano: 2020,
      cor: 'Branca',
      cpf: null,
    },
    {
      id: 101,
      marca: 'Triumph',
      modelo: 'Bonneville',
      ano: 2018,
      cor: 'Verde',
      cpf: null,
    },
    {
      id: 376,
      marca: 'Yamaha',
      modelo: 'Tracer 900',
      ano: 2019,
      cor: 'Azul',
      cpf: null,
    },
    {
      id: 184,
      marca: 'Kawasaki',
      modelo: 'Versys 650',
      ano: 2021,
      cor: 'Verde',
      cpf: null,
    },
    {
      id: 231,
      marca: 'Suzuki',
      modelo: 'V-Strom 650',
      ano: 2020,
      cor: 'Amarela',
      cpf: null,
    },
    {
      id: 498,
      marca: 'Harley-Davidson',
      modelo: 'Sportster',
      ano: 2019,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 345,
      marca: 'Ducati',
      modelo: 'Diavel 1260',
      ano: 2021,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 109,
      marca: 'BMW',
      modelo: 'F 850 GS',
      ano: 2020,
      cor: 'Branca',
      cpf: null,
    },
    {
      id: 203,
      marca: 'KTM',
      modelo: 'Super Duke 1290',
      ano: 2018,
      cor: 'Laranja',
      cpf: null,
    },
    {
      id: 187,
      marca: 'Triumph',
      modelo: 'Speed Twin',
      ano: 2021,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 291,
      marca: 'Honda',
      modelo: 'CB 650R',
      ano: 2020,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 412,
      marca: 'Suzuki',
      modelo: 'GSX-R1000',
      ano: 2021,
      cor: 'Azul',
      cpf: null,
    },
    {
      id: 175,
      marca: 'Kawasaki',
      modelo: 'Z650',
      ano: 2019,
      cor: 'Verde',
      cpf: null,
    },
    {
      id: 64,
      marca: 'Harley-Davidson',
      modelo: 'Road King',
      ano: 2018,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 344,
      marca: 'BMW',
      modelo: 'R nineT',
      ano: 2020,
      cor: 'Branca',
      cpf: null,
    },
    {
      id: 220,
      marca: 'Honda',
      modelo: 'CB 500X',
      ano: 2019,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 128,
      marca: 'Yamaha',
      modelo: 'XSR 900',
      ano: 2021,
      cor: 'Azul',
      cpf: null,
    },
    {
      id: 401,
      marca: 'Suzuki',
      modelo: 'GSX-S1000',
      ano: 2020,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 147,
      marca: 'Triumph',
      modelo: 'Street Scrambler',
      ano: 2020,
      cor: 'Verde',
      cpf: null,
    },
    {
      id: 338,
      marca: 'Kawasaki',
      modelo: 'Z1000',
      ano: 2021,
      cor: 'Verde',
      cpf: null,
    },
    {
      id: 178,
      marca: 'Honda',
      modelo: 'CB 300R',
      ano: 2021,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 234,
      marca: 'Suzuki',
      modelo: 'Katana',
      ano: 2020,
      cor: 'Prata',
      cpf: null,
    },
    {
      id: 97,
      marca: 'BMW',
      modelo: 'G 310 GS',
      ano: 2019,
      cor: 'Branca',
      cpf: null,
    },
    {
      id: 120,
      marca: 'Ducati',
      modelo: 'Multistrada 950',
      ano: 2018,
      cor: 'Vermelha',
      cpf: null,
    },
    {
      id: 154,
      marca: 'Triumph',
      modelo: 'Thruxton',
      ano: 2021,
      cor: 'Preta',
      cpf: null,
    },
    {
      id: 299,
      marca: 'Harley-Davidson',
      modelo: 'Softail',
      ano: 2020,
      cor: 'Cinza',
      cpf: null,
    },
    {
      id: 432,
      marca: 'Yamaha',
      modelo: 'Tenere 700',
      ano: 2021,
      cor: 'Azul',
      cpf: null,
    },
    {
      id: 75,
      marca: 'Suzuki',
      modelo: 'Burgman 400',
      ano: 2018,
      cor: 'Prata',
      cpf: null,
    },
  ];

  for (const moto of motos) {
    await prisma.moto.upsert({
      where: { id: moto.id },
      update: moto,
      create: moto,
    });
  }

  await prisma.consertoDeMotos.deleteMany({});
  await prisma.consertoDeMotos.createMany({
    data: [
      {
        motoId: 34,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(2024, 10, 7),
        mecanicoId: 2,
      },
      {
        motoId: 294,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: 3,
        dataEntrada: new Date(2024, 10, 7),
        mecanicoId: 1,
      },
      {
        motoId: 314,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 2,
        dataEntrada: new Date(2024, 10, 7),
        mecanicoId: 7,
      },
      {
        motoId: 488,
        complexidadeDoConserto: 3,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(2024, 10, 7),
        mecanicoId: 6,
      },
      {
        motoId: 123,
        complexidadeDoConserto: 2,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(2024, 10, 7),
        mecanicoId: 4,
      },
      {
        motoId: 221,
        complexidadeDoConserto: 1,
        tipoConsertoId: 1,
        tempoReal: 2,
        dataEntrada: new Date(2024, 10, 7),
        mecanicoId: 10,
      },
      {
        motoId: 456,
        complexidadeDoConserto: 3,
        tipoConsertoId: 5,
        tempoReal: 5,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 9,
      },
      {
        motoId: 89,
        complexidadeDoConserto: 2,
        tipoConsertoId: 2,
        tempoReal: 6,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 8,
      },
      {
        motoId: 190,
        complexidadeDoConserto: 1,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 7,
      },
      {
        motoId: 402,
        complexidadeDoConserto: 2,
        tipoConsertoId: 3,
        tempoReal: 3,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 1,
      },
      {
        motoId: 76,
        complexidadeDoConserto: 1,
        tipoConsertoId: 1,
        tempoReal: 4,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 10,
      },
      {
        motoId: 320,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 5,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 8,
      },
      {
        motoId: 145,
        complexidadeDoConserto: 3,
        tipoConsertoId: 2,
        tempoReal: 6,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 6,
      },
      {
        motoId: 67,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 1,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 2,
      },
      {
        motoId: 290,
        complexidadeDoConserto: 2,
        tipoConsertoId: 4,
        tempoReal: 2,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 4,
      },
      {
        motoId: 112,
        complexidadeDoConserto: 1,
        tipoConsertoId: 5,
        tempoReal: 4,
        dataEntrada: new Date(2024, 11, 7),
        mecanicoId: 7,
      },
      {
        motoId: 404,
        complexidadeDoConserto: 3,
        tipoConsertoId: 2,
        tempoReal: 1,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 9,
      },
      {
        motoId: 310,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 2,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 3,
      },
      {
        motoId: 22,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: 4,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 8,
      },
      {
        motoId: 459,
        complexidadeDoConserto: 3,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 6,
      },
      {
        motoId: 134,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 3,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 4,
      },
      {
        motoId: 293,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 2,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 10,
      },
      {
        motoId: 378,
        complexidadeDoConserto: 3,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 6,
      },
      {
        motoId: 101,
        complexidadeDoConserto: 1,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 7,
      },
      {
        motoId: 488,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: 3,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 8,
      },
      {
        motoId: 376,
        complexidadeDoConserto: 3,
        tipoConsertoId: 5,
        tempoReal: 5,
        dataEntrada: new Date(2024, 12, 7),
        mecanicoId: 9,
      },
      {
        motoId: 184,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 6,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 2,
      },
      {
        motoId: 231,
        complexidadeDoConserto: 2,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 1,
      },
      {
        motoId: 498,
        complexidadeDoConserto: 1,
        tipoConsertoId: 4,
        tempoReal: 2,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 10,
      },
      {
        motoId: 345,
        complexidadeDoConserto: 3,
        tipoConsertoId: 1,
        tempoReal: 1,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 9,
      },
      {
        motoId: 109,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 3,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 4,
      },
      {
        motoId: 203,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 2,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 7,
      },
      {
        motoId: 402,
        complexidadeDoConserto: 3,
        tipoConsertoId: 2,
        tempoReal: 4,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 3,
      },
      {
        motoId: 187,
        complexidadeDoConserto: 1,
        tipoConsertoId: 5,
        tempoReal: 1,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 2,
      },
      {
        motoId: 291,
        complexidadeDoConserto: 2,
        tipoConsertoId: 4,
        tempoReal: 3,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 8,
      },
      {
        motoId: 412,
        complexidadeDoConserto: 3,
        tipoConsertoId: 1,
        tempoReal: 5,
        dataEntrada: new Date(2024, 13, 7),
        mecanicoId: 6,
      },
      {
        motoId: 175,
        complexidadeDoConserto: 2,
        tipoConsertoId: 3,
        tempoReal: 6,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 4,
      },
      {
        motoId: 64,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 4,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 7,
      },
      {
        motoId: 344,
        complexidadeDoConserto: 3,
        tipoConsertoId: 4,
        tempoReal: 1,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 3,
      },
      {
        motoId: 220,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 3,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 1,
      },
      {
        motoId: 128,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 2,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 10,
      },
      {
        motoId: 376,
        complexidadeDoConserto: 3,
        tipoConsertoId: 2,
        tempoReal: 1,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 9,
      },
      {
        motoId: 401,
        complexidadeDoConserto: 1,
        tipoConsertoId: 4,
        tempoReal: 4,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 2,
      },
      {
        motoId: 147,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: 5,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 8,
      },
      {
        motoId: 338,
        complexidadeDoConserto: 3,
        tipoConsertoId: 3,
        tempoReal: 6,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 6,
      },
      {
        motoId: 178,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: 1,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 7,
      },
      {
        motoId: 234,
        complexidadeDoConserto: 2,
        tipoConsertoId: 5,
        tempoReal: 3,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 4,
      },
      {
        motoId: 97,
        complexidadeDoConserto: 3,
        tipoConsertoId: 4,
        tempoReal: 2,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 9,
      },
      {
        motoId: 120,
        complexidadeDoConserto: 1,
        tipoConsertoId: 3,
        tempoReal: 4,
        dataEntrada: new Date(2024, 14, 7),
        mecanicoId: 3,
      },
      {
        motoId: 221,
        complexidadeDoConserto: 2,
        tipoConsertoId: 1,
        tempoReal: null,
        dataEntrada: new Date(2024, 15, 7),
        mecanicoId: null,
      },
      {
        motoId: 154,
        complexidadeDoConserto: 3,
        tipoConsertoId: 5,
        tempoReal: null,
        dataEntrada: new Date(2024, 15, 7),
        mecanicoId: null,
      },
      {
        motoId: 299,
        complexidadeDoConserto: 1,
        tipoConsertoId: 2,
        tempoReal: null,
        dataEntrada: new Date(2024, 15, 7),
        mecanicoId: null,
      },
      {
        motoId: 432,
        complexidadeDoConserto: 2,
        tipoConsertoId: 4,
        tempoReal: null,
        dataEntrada: new Date(2024, 15, 7),
        mecanicoId: null,
      },
      {
        motoId: 75,
        complexidadeDoConserto: 3,
        tipoConsertoId: 3,
        tempoReal: null,
        dataEntrada: new Date(2024, 15, 7),
        mecanicoId: null,
      },
    ],
  });
}

main()
  .then(() => {
    console.log('Seed data created');
  })
  .catch((error) => {
    console.error(error);
  })
  .finally(() => {
    prisma.$disconnect();
  });
